# **AMOSTRAGENS**

In [1]:
import numpy as np
import pandas as pd

In [5]:
#enem_sp = pd.read_csv('/content/drive/MyDrive/Cursos_Udemy/curso_estatistica_python/enem_2019_tratado.csv',
#                      sep=',', encoding='iso-8859-1')

In [3]:
enem_sp = pd.read_csv('/content/enem_2019_tratado.csv',sep=',', encoding='iso-8859-1')

In [6]:
enem_sp.head()

NU_INSCRICAO NO_MUNICIPIO_RESIDENCIA  IDADE  ...  COMP5  NOTA_REDACAO INTERNET
0     1,90E+11            Santa Isabel     22  ...  200.0         940.0      Sim
1     1,90E+11               São Paulo     17  ...  200.0         880.0      Não
2     1,90E+11   São Bernardo do Campo     19  ...  100.0         560.0      Sim
3     1,90E+11              Embu-Guaçu     17  ...   80.0         560.0      Sim
4     1,90E+11               Guarulhos     23  ...  160.0         880.0      Sim

[5 rows x 28 columns]

In [8]:
# criamos uma tabela de dados  com nome "enem_campinas"
enem_campinas = enem_sp.loc[enem_sp.NO_MUNICIPIO_RESIDENCIA == 'Campinas']

In [9]:
enem_campinas.head(10)

NU_INSCRICAO NO_MUNICIPIO_RESIDENCIA  IDADE  ...  COMP5  NOTA_REDACAO INTERNET
15      1,90E+11                Campinas     17  ...  120.0         680.0      Sim
31      1,90E+11                Campinas     19  ...  160.0         720.0      Sim
51      1,90E+11                Campinas     17  ...  160.0         740.0      Sim
116     1,90E+11                Campinas     17  ...    0.0         340.0      Sim
169     1,90E+11                Campinas     17  ...  160.0         720.0      Sim
186     1,90E+11                Campinas     19  ...   80.0         560.0      Sim
236     1,90E+11                Campinas     17  ...  200.0         760.0      Sim
325     1,90E+11                Campinas     17  ...   80.0         480.0      Sim
401     1,90E+11                Campinas     18  ...  200.0         860.0      Sim
469     1,90E+11                Campinas     18  ...  120.0         720.0      Sim

[10 rows x 28 columns]

In [10]:
enem_campinas.shape

(13198, 28)

## **AMOSTRAGEM ALEATÓRIA SIMPLES**

In [11]:
# temos uma semente aleatoria
#obtemos as mesmas respostas para aquela amostragem
np.random.seed(1)

In [12]:
# Creamos uma nova variável "amos_simples" onde "(frac=0.20)" significa
# que vamos toma uma fração ou 20% das amostras aleatórias
amos_simples = enem_campinas.sample(frac=0.20) # Porcentagem

In [13]:
amos_simples

NU_INSCRICAO NO_MUNICIPIO_RESIDENCIA  ...  NOTA_REDACAO INTERNET
327999     1,90E+11                Campinas  ...         960.0      Sim
235222     1,90E+11                Campinas  ...         780.0      Sim
134221     1,90E+11                Campinas  ...         500.0      Sim
358407     1,90E+11                Campinas  ...         660.0      Não
173364     1,90E+11                Campinas  ...         620.0      Sim
...             ...                     ...  ...           ...      ...
452747     1,90E+11                Campinas  ...         400.0      Sim
362918     1,90E+11                Campinas  ...         320.0      Sim
221397     1,90E+11                Campinas  ...         580.0      Sim
76628      1,90E+11                Campinas  ...         560.0      Sim
126402     1,90E+11                Campinas  ...         680.0      Sim

[2640 rows x 28 columns]

In [14]:
amos_simples = enem_campinas.sample(3000) # Quantidade numérica

In [15]:
amos_simples

NU_INSCRICAO NO_MUNICIPIO_RESIDENCIA  ...  NOTA_REDACAO INTERNET
57191      1,90E+11                Campinas  ...         620.0      Sim
215078     1,90E+11                Campinas  ...         580.0      Sim
430770     1,90E+11                Campinas  ...         760.0      Sim
409180     1,90E+11                Campinas  ...         620.0      Sim
429862     1,90E+11                Campinas  ...         640.0      Sim
...             ...                     ...  ...           ...      ...
238949     1,90E+11                Campinas  ...         780.0      Sim
242711     1,90E+11                Campinas  ...         800.0      Sim
467039     1,90E+11                Campinas  ...         500.0      Sim
189967     1,90E+11                Campinas  ...         620.0      Não
282921     1,90E+11                Campinas  ...         660.0      Sim

[3000 rows x 28 columns]

**OUTRA MANEIRA**

In [16]:
np.random.seed(2)

In [17]:
amostra = np.random.choice(a=[0,1], size=13198, replace=True, p=[0.8, 0.2])

In [18]:
amostra

array([0, 0, 0, ..., 0, 0, 1])

In [19]:
len(amostra[amostra == 0])

10566

In [20]:
len(amostra[amostra == 1])

2632

In [21]:
amos_simples = enem_campinas.loc[amostra == 1]

In [22]:
amos_simples

NU_INSCRICAO NO_MUNICIPIO_RESIDENCIA  ...  NOTA_REDACAO INTERNET
949        1,90E+11                Campinas  ...         660.0      Sim
1058       1,90E+11                Campinas  ...         620.0      Sim
1980       1,90E+11                Campinas  ...         620.0      Não
2053       1,90E+11                Campinas  ...         240.0      Sim
2328       1,90E+11                Campinas  ...         520.0      Sim
...             ...                     ...  ...           ...      ...
498946     1,90E+11                Campinas  ...         560.0      Sim
499198     1,90E+11                Campinas  ...         540.0      Sim
499258     1,90E+11                Campinas  ...         620.0      Sim
499691     1,90E+11                Campinas  ...         600.0      Sim
499883     1,90E+11                Campinas  ...         940.0      Sim

[2632 rows x 28 columns]

## **AMOSTRAGEM SISTEMÁTICA**

In [23]:
enem_campinas.shape

(13198, 28)

In [24]:
np.random.seed(2)
inicio = np.random.choice(10, 1)

In [25]:
inicio

array([8])

In [26]:
amostra2 = np.arange(inicio,13198,100)
amostra2

array([    8,   108,   208,   308,   408,   508,   608,   708,   808,
         908,  1008,  1108,  1208,  1308,  1408,  1508,  1608,  1708,
        1808,  1908,  2008,  2108,  2208,  2308,  2408,  2508,  2608,
        2708,  2808,  2908,  3008,  3108,  3208,  3308,  3408,  3508,
        3608,  3708,  3808,  3908,  4008,  4108,  4208,  4308,  4408,
        4508,  4608,  4708,  4808,  4908,  5008,  5108,  5208,  5308,
        5408,  5508,  5608,  5708,  5808,  5908,  6008,  6108,  6208,
        6308,  6408,  6508,  6608,  6708,  6808,  6908,  7008,  7108,
        7208,  7308,  7408,  7508,  7608,  7708,  7808,  7908,  8008,
        8108,  8208,  8308,  8408,  8508,  8608,  8708,  8808,  8908,
        9008,  9108,  9208,  9308,  9408,  9508,  9608,  9708,  9808,
        9908, 10008, 10108, 10208, 10308, 10408, 10508, 10608, 10708,
       10808, 10908, 11008, 11108, 11208, 11308, 11408, 11508, 11608,
       11708, 11808, 11908, 12008, 12108, 12208, 12308, 12408, 12508,
       12608, 12708,

In [27]:
amos_sistematica = enem_campinas.iloc[amostra2,:]

In [ ]:
amos_sistematica

NU_INSCRICAO NO_MUNICIPIO_RESIDENCIA  ...  NOTA_REDACAO INTERNET
401        1,90E+11                Campinas  ...         860.0      Sim
5079       1,90E+11                Campinas  ...         640.0      Sim
9218       1,90E+11                Campinas  ...         600.0      Sim
13685      1,90E+11                Campinas  ...         920.0      Sim
18239      1,90E+11                Campinas  ...         960.0      Sim
...             ...                     ...  ...           ...      ...
481894     1,90E+11                Campinas  ...         740.0      Sim
485805     1,90E+11                Campinas  ...         460.0      Sim
488958     1,90E+11                Campinas  ...         680.0      Sim
492626     1,90E+11                Campinas  ...         460.0      Sim
496410     1,90E+11                Campinas  ...         380.0      Sim

[132 rows x 28 columns]

**OUTRA MANEIRA**

In [28]:
np.random.seed(30)

In [29]:
inicio = np.random.choice(10, 1)
passo = np.random.randint(100, 150, 1)

In [30]:
inicio

array([5])

In [31]:
passo

array([137])

In [32]:
amostra2 = np.arange(inicio,13198,passo)
amostra2

array([    5,   142,   279,   416,   553,   690,   827,   964,  1101,
        1238,  1375,  1512,  1649,  1786,  1923,  2060,  2197,  2334,
        2471,  2608,  2745,  2882,  3019,  3156,  3293,  3430,  3567,
        3704,  3841,  3978,  4115,  4252,  4389,  4526,  4663,  4800,
        4937,  5074,  5211,  5348,  5485,  5622,  5759,  5896,  6033,
        6170,  6307,  6444,  6581,  6718,  6855,  6992,  7129,  7266,
        7403,  7540,  7677,  7814,  7951,  8088,  8225,  8362,  8499,
        8636,  8773,  8910,  9047,  9184,  9321,  9458,  9595,  9732,
        9869, 10006, 10143, 10280, 10417, 10554, 10691, 10828, 10965,
       11102, 11239, 11376, 11513, 11650, 11787, 11924, 12061, 12198,
       12335, 12472, 12609, 12746, 12883, 13020, 13157])

In [33]:
amostra2_camp = enem_campinas.iloc[amostra2,:]

In [34]:
amostra2_camp

NU_INSCRICAO NO_MUNICIPIO_RESIDENCIA  ...  NOTA_REDACAO INTERNET
186        1,90E+11                Campinas  ...         560.0      Sim
6519       1,90E+11                Campinas  ...         780.0      Não
12280      1,90E+11                Campinas  ...         440.0      Sim
18436      1,90E+11                Campinas  ...         520.0      Sim
23717      1,90E+11                Campinas  ...         320.0      Sim
...             ...                     ...  ...           ...      ...
478519     1,90E+11                Campinas  ...         680.0      Sim
483431     1,90E+11                Campinas  ...         620.0      Sim
488340     1,90E+11                Campinas  ...         580.0      Sim
493180     1,90E+11                Campinas  ...         240.0      Sim
498126     1,90E+11                Campinas  ...         540.0      Sim

[97 rows x 28 columns]

## **AMOSTRAGEM ESTRATIFICADA**

In [35]:
enem_campinas['RACA'].value_counts()

branca           7507
parda            3652
preta            1510
amarela           279
nao_declarado     205
indígena           45
Name: RACA, dtype: int64

**Para quantidade pequena de grupos**

In [36]:
branca = enem_campinas.loc[enem_campinas.RACA == 'branca'].sample(frac=0.15)
branca.shape

(1126, 28)

In [37]:
parda = enem_campinas.loc[enem_campinas.RACA == 'parda'].sample(frac=0.15)
parda.shape

(548, 28)

In [38]:
preta = enem_campinas.loc[enem_campinas.RACA == 'preta'].sample(frac=0.15)
preta.shape

(226, 28)

In [39]:
amarela = enem_campinas.loc[enem_campinas.RACA == 'amarela'].sample(frac=0.15)
amarela.shape

(42, 28)

In [40]:
nd = enem_campinas.loc[enem_campinas.RACA == 'nao_declarado'].sample(frac=0.15)
nd.shape

(31, 28)

In [41]:
indigena = enem_campinas.loc[enem_campinas.RACA == 'indígena'].sample(frac=0.15)
indigena.shape

(7, 28)

In [42]:
indigena

NU_INSCRICAO NO_MUNICIPIO_RESIDENCIA  ...  NOTA_REDACAO INTERNET
88722      1,90E+11                Campinas  ...         400.0      Sim
315951     1,90E+11                Campinas  ...         620.0      Sim
270535     1,90E+11                Campinas  ...         760.0      Sim
88212      1,90E+11                Campinas  ...         640.0      Sim
349878     1,90E+11                Campinas  ...         620.0      Sim
22882      1,90E+11                Campinas  ...         740.0      Sim
210698     1,90E+11                Campinas  ...         560.0      Sim

[7 rows x 28 columns]

In [43]:
amos_estra = pd.concat([branca, parda, preta, amarela, nd, indigena])

In [44]:
amos_estra

NU_INSCRICAO NO_MUNICIPIO_RESIDENCIA  ...  NOTA_REDACAO INTERNET
439942     1,90E+11                Campinas  ...         560.0      Sim
477692     1,90E+11                Campinas  ...         440.0      Sim
398248     1,90E+11                Campinas  ...           0.0      Sim
121597     1,90E+11                Campinas  ...         600.0      Sim
316202     1,90E+11                Campinas  ...         540.0      Sim
...             ...                     ...  ...           ...      ...
270535     1,90E+11                Campinas  ...         760.0      Sim
88212      1,90E+11                Campinas  ...         640.0      Sim
349878     1,90E+11                Campinas  ...         620.0      Sim
22882      1,90E+11                Campinas  ...         740.0      Sim
210698     1,90E+11                Campinas  ...         560.0      Sim

[1980 rows x 28 columns]

**Grandes quantidades de grupos**

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
X_treino, X_teste, y_treino, amos_estra = train_test_split(enem_campinas.drop('RACA',axis=1),enem_campinas['RACA'],
                                                    stratify=enem_campinas['RACA'], test_size=0.20)

In [47]:
amos_estra.shape

(2640,)

In [48]:
amos_estra.value_counts()

branca           1502
parda             730
preta             302
amarela            56
nao_declarado      41
indígena            9
Name: RACA, dtype: int64

In [49]:
amos_estra = amos_estra.index

In [50]:
amos_estra

Int64Index([354701, 171454,  80882,  74736, 200886,  42542, 162154,  43460,
            173204, 245995,
            ...
            497532, 328798, 484300, 292798, 239869, 310618, 486071, 172689,
            109357, 145729],
           dtype='int64', length=2640)

In [51]:
amos_estra_camp = enem_campinas.loc[amos_estra,:]

In [52]:
amos_estra_camp

NU_INSCRICAO NO_MUNICIPIO_RESIDENCIA  ...  NOTA_REDACAO INTERNET
354701     1,90E+11                Campinas  ...         880.0      Sim
171454     1,90E+11                Campinas  ...         540.0      Sim
80882      1,90E+11                Campinas  ...         520.0      Sim
74736      1,90E+11                Campinas  ...         540.0      Sim
200886     1,90E+11                Campinas  ...         700.0      Sim
...             ...                     ...  ...           ...      ...
310618     1,90E+11                Campinas  ...         420.0      Sim
486071     1,90E+11                Campinas  ...         460.0      Não
172689     1,90E+11                Campinas  ...         520.0      Sim
109357     1,90E+11                Campinas  ...         660.0      Sim
145729     1,90E+11                Campinas  ...         920.0      Sim

[2640 rows x 28 columns]

## **AMOSTRAGEM POR CONGLOMERADO (AGRUPAMENTO)**

In [53]:
escolas_publicas = enem_campinas.loc[enem_campinas.ESCOLA == 'pública']

In [54]:
escolas_publicas.shape

(4175, 28)

In [55]:
escolas_publicas

NU_INSCRICAO NO_MUNICIPIO_RESIDENCIA  ...  NOTA_REDACAO INTERNET
51         1,90E+11                Campinas  ...         740.0      Sim
116        1,90E+11                Campinas  ...         340.0      Sim
325        1,90E+11                Campinas  ...         480.0      Sim
949        1,90E+11                Campinas  ...         660.0      Sim
1004       1,90E+11                Campinas  ...         420.0      Não
...             ...                     ...  ...           ...      ...
499530     1,90E+11                Campinas  ...         660.0      Sim
499640     1,90E+11                Campinas  ...         280.0      Sim
499691     1,90E+11                Campinas  ...         600.0      Sim
499749     1,90E+11                Campinas  ...         440.0      Sim
499862     1,90E+11                Campinas  ...         640.0      Sim

[4175 rows x 28 columns]

In [56]:
amostras = escolas_publicas['CO_ESCOLA'].value_counts()
amostras

35045937.0    152
35018363.0    134
35018797.0    124
35018879.0    110
35018326.0    109
             ... 
35126846.0      1
35112252.0      1
26078562.0      1
35039834.0      1
35016559.0      1
Name: CO_ESCOLA, Length: 186, dtype: int64

In [57]:
amostras.index

Float64Index([35045937.0, 35018363.0, 35018797.0, 35018879.0, 35018326.0,
              35047200.0, 35901097.0, 35045949.0, 35018235.0, 35018302.0,
              ...
              35045962.0, 35112773.0, 35924672.0, 35042523.0, 35018181.0,
              35126846.0, 35112252.0, 26078562.0, 35039834.0, 35016559.0],
             dtype='float64', length=186)

In [58]:
amostragem = np.random.choice(a=[0,1],size=186, replace=True, p=[0.85, 0.15])

In [59]:
amostragem

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [60]:
amos_conglomerado = amostras.loc[amostragem == 1]

In [61]:
amos_conglomerado

35018797.0    124
35018326.0    109
35018284.0     43
35112859.0     39
35924544.0     30
35905461.0     27
35018922.0     23
35125568.0     19
35040873.0     15
35127012.0     14
35018417.0     13
35913923.0      9
35065535.0      9
35437153.0      7
35112720.0      6
35165062.0      4
35011343.0      3
35564990.0      2
35800387.0      1
26127741.0      1
35445757.0      1
35035956.0      1
35112689.0      1
35018181.0      1
Name: CO_ESCOLA, dtype: int64

In [62]:
amos_conglomerado.shape

(24,)

In [63]:
amos_conglomerado.index

Float64Index([35018797.0, 35018326.0, 35018284.0, 35112859.0, 35924544.0,
              35905461.0, 35018922.0, 35125568.0, 35040873.0, 35127012.0,
              35018417.0, 35913923.0, 35065535.0, 35437153.0, 35112720.0,
              35165062.0, 35011343.0, 35564990.0, 35800387.0, 26127741.0,
              35445757.0, 35035956.0, 35112689.0, 35018181.0],
             dtype='float64')

In [64]:
amos_conglomerado = escolas_publicas.loc[escolas_publicas['CO_ESCOLA'].isin([35112859.0, 35905471.0, 35045950.0, 35018508.0, 35905461.0,
              35914897.0, 35125568.0, 35127012.0, 35037965.0, 35018910.0,
              35127784.0, 35925962.0, 35907397.0, 35118084.0, 35579403.0,
              35458569.0, 35985296.0, 35045724.0, 35150095.0, 35138769.0,
              35337833.0, 35500012.0, 26127741.0, 35462342.0, 35445757.0,
              35058836.0, 35035956.0])]

In [65]:
amos_conglomerado

NU_INSCRICAO NO_MUNICIPIO_RESIDENCIA  ...  NOTA_REDACAO INTERNET
2066       1,90E+11                Campinas  ...         940.0      Sim
5050       1,90E+11                Campinas  ...         720.0      Sim
5267       1,90E+11                Campinas  ...         560.0      Sim
6279       1,90E+11                Campinas  ...         460.0      Sim
6389       1,90E+11                Campinas  ...         580.0      Sim
...             ...                     ...  ...           ...      ...
481186     1,90E+11                Campinas  ...         540.0      Sim
487155     1,90E+11                Campinas  ...         480.0      Sim
491722     1,90E+11                Campinas  ...         300.0      Sim
493548     1,90E+11                Campinas  ...         700.0      Sim
499026     1,90E+11                Campinas  ...         320.0      Sim

[293 rows x 28 columns]